automations:
  - name: "Terraform Init"
    description: "Initialize Terraform configuration"
    command: "terraform init"
    trigger:
      on_workspace_start: true
      on_file_change:
        patterns: ["*.tf"]
        ignore_patterns: ["*.tfvars"]
        debounce: 5000

  - name: "Terraform Validate"
    description: "Validate Terraform configuration"
    command: "terraform validate"
    trigger:
      on_file_change:
        patterns: ["*.tf"]
        ignore_patterns: ["*.tfvars"]
        debounce: 5000

  - name: "AWS Authentication Setup"
    description: "Set up AWS authentication using environment variables"
    command: |
      if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
        echo "AWS credentials are set. Authentication should work."
      else
        echo "AWS credentials are not set. Please set the following environment variables:"
        echo "AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY"
        echo "AWS_DEFAULT_REGION (optional, defaults to us-east-1)"
      fi
    trigger:
      on_workspace_start: true

  - name: "Terraform Cleanup"
    description: "Destroy all AWS resources created by Terraform"
    command: |
      echo "WARNING: This will destroy all AWS resources created by Terraform."
      echo "Press Ctrl+C within 5 seconds to cancel."
      sleep 5
      terraform destroy -auto-approve
    trigger:
      manual: true
